### ISSUE TITLE
Support Blue Skies

### ISSUE THREAD

**Issue by NordicGamerFE** [ZZZank/JEIAreaFixer#4]
Hey the side bars of blue skies currently overlap JEI
![image](https://github.com/user-attachments/assets/423d2deb-e6d6-4ce8-9fda-66828a7a69de)

**Comment by ZZZank** [comment]
Support for BlueSkies tab will be added in the next release.

And I wanna ask a question, are there any other BlueSkies GUIs that will overlap with JEI? I didn't found any in my test, but it can be me missing something

**Comment by NordicGamerFE** [comment]
i'll go ingame and check, and while i am checking i'll check all the mods in my pack and see if i find any issues.

**Comment by NordicGamerFE** [comment]
blue skies does not have any other overlaps

**Comment by ZZZank** [comment]
1.6.0 is released now


https://github.com/user-attachments/assets/6e6c83a4-1912-4814-b91b-dc0108e38aa9
