### ISSUE TITLE
Support Trinkets and Baubles

### ISSUE THREAD

**Issue by NordicGamerFE** [ZZZank/JEIAreaFixer#5]
![image](https://github.com/user-attachments/assets/999962dd-6300-48ba-a75a-d4d15ac4684a)
https://www.curseforge.com/minecraft/mc-mods/trinkets-and-baubles

**Comment by ZZZank** [comment]
I've done some investigation of this mod, and to be honest, the slot rendering code of Trinkets and Baubles looks horrible, so it might take me some additional time to figure out how to support this mod

**Comment by ZZZank** [comment]
supported in 1.6.0

<img width="394" alt="tab" src="https://github.com/user-attachments/assets/0dad4dbd-bb64-4e74-8587-3dc4b74c5ce8">
