### ISSUE TITLE
Support Crafting Tweaks Unofficial

### ISSUE THREAD

**Issue by NordicGamerFE** [ZZZank/JEIAreaFixer#6]
![image](https://github.com/user-attachments/assets/62770bb7-729f-4dcc-9383-d1b9cc6bb7e9)
https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks-unofficial

**Comment by ZZZank** [comment]
Crafting Tweaks support will be added in the next release

<img width="400" alt="extCrafting" src="https://github.com/user-attachments/assets/62ebcca7-29a8-4e90-b811-1703a82620c8">

**Comment by ZZZank** [comment]
supported in 1.6.0
