### ISSUE TITLE
Support for several AE2 addons

### ISSUE THREAD

**Issue by NordicGamerFE** [ZZZank/JEIAreaFixer#7]
![image](https://github.com/user-attachments/assets/e73d1aea-ee20-42d5-a704-d1d23347e135)
![image](https://github.com/user-attachments/assets/1c4af0bd-ea66-407d-9e1d-ae90db4d460c)
![image](https://github.com/user-attachments/assets/b775b72d-f349-47b7-9d7c-ead2467ae930)
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2
https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life
https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal
https://www.curseforge.com/minecraft/mc-mods/wireless-pattern-terminal
https://www.curseforge.com/minecraft/mc-mods/wireless-interface-terminal
https://www.curseforge.com/minecraft/mc-mods/wireless-fluid-terminal

**Comment by ZZZank** [comment]
This should not happen in the newest version of JEI Area Fixer.

AE2 support is introduced in 1.5.0, but it will automatically disable itself when AE2UEL is installed, are you using AE2UEL?

**Comment by NordicGamerFE** [comment]
You would be correct i did some additonal testing and you would be correct ae2uel was the issue but the issue is still an issue with the additonal terminals mods i linked and i would bet in that case some other ae2 addons might also have issues

**Comment by NordicGamerFE** [comment]
i tested most of the addons and was not able to find another issue

**Comment by NordicGamerFE** [comment]
Here are the links to all the trouble mods
https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal
https://www.curseforge.com/minecraft/mc-mods/wireless-pattern-terminal
https://www.curseforge.com/minecraft/mc-mods/wireless-interface-terminal
https://www.curseforge.com/minecraft/mc-mods/wireless-fluid-terminal

**Comment by ZZZank** [comment]
supported in 1.6.0

<img width="392" alt="terminal" src="https://github.com/user-attachments/assets/d670f59d-c976-4824-8097-438e929fa6d7">
